// Sample enterprise knowledge graph (entities + relationships) for multi-hop demos.
// Usage with cypher-shell:
//   cypher-shell -u neo4j -p <password> --param "tenant_id => '<tenant uuid>'" -f /import/scripts/seed.cypher
// Prefer `make seed`: it ingests the sample documents through the real pipeline so chunks,
// embeddings and citations exist as well. This script loads only the entity graph (no APOC needed).

MERGE (e:Entity:Person {id: 'seed_' + $tenant_id + '_rahul'}) SET e.tenant_id = $tenant_id, e.name = 'Rahul', e.type = 'Person', e.normalized_name = 'rahul', e.aliases = [], e.aliases_text = '', e.document_ids = ['seed'];
MERGE (e:Entity:Person {id: 'seed_' + $tenant_id + '_amit'}) SET e.tenant_id = $tenant_id, e.name = 'Amit', e.type = 'Person', e.normalized_name = 'amit', e.aliases = [], e.aliases_text = '', e.document_ids = ['seed'];
MERGE (e:Entity:Person {id: 'seed_' + $tenant_id + '_priya'}) SET e.tenant_id = $tenant_id, e.name = 'Priya', e.type = 'Person', e.normalized_name = 'priya', e.aliases = [], e.aliases_text = '', e.document_ids = ['seed'];
MERGE (e:Entity:Person {id: 'seed_' + $tenant_id + '_neha'}) SET e.tenant_id = $tenant_id, e.name = 'Neha', e.type = 'Person', e.normalized_name = 'neha', e.aliases = [], e.aliases_text = '', e.document_ids = ['seed'];
MERGE (e:Entity:Project {id: 'seed_' + $tenant_id + '_project_alpha'}) SET e.tenant_id = $tenant_id, e.name = 'Project Alpha', e.type = 'Project', e.normalized_name = 'project alpha', e.aliases = [], e.aliases_text = '', e.document_ids = ['seed'];
MERGE (e:Entity:Project {id: 'seed_' + $tenant_id + '_project_beta'}) SET e.tenant_id = $tenant_id, e.name = 'Project Beta', e.type = 'Project', e.normalized_name = 'project beta', e.aliases = [], e.aliases_text = '', e.document_ids = ['seed'];
MERGE (e:Entity:Project {id: 'seed_' + $tenant_id + '_project_gamma'}) SET e.tenant_id = $tenant_id, e.name = 'Project Gamma', e.type = 'Project', e.normalized_name = 'project gamma', e.aliases = [], e.aliases_text = '', e.document_ids = ['seed'];
MERGE (e:Entity:Technology {id: 'seed_' + $tenant_id + '_kafka'}) SET e.tenant_id = $tenant_id, e.name = 'Kafka', e.type = 'Technology', e.normalized_name = 'kafka', e.aliases = [], e.aliases_text = '', e.document_ids = ['seed'];
MERGE (e:Entity:Technology {id: 'seed_' + $tenant_id + '_redis'}) SET e.tenant_id = $tenant_id, e.name = 'Redis', e.type = 'Technology', e.normalized_name = 'redis', e.aliases = [], e.aliases_text = '', e.document_ids = ['seed'];
MERGE (e:Entity:Technology {id: 'seed_' + $tenant_id + '_postgresql'}) SET e.tenant_id = $tenant_id, e.name = 'PostgreSQL', e.type = 'Technology', e.normalized_name = 'postgresql', e.aliases = [], e.aliases_text = '', e.document_ids = ['seed'];
MERGE (e:Entity:Technology {id: 'seed_' + $tenant_id + '_fastapi'}) SET e.tenant_id = $tenant_id, e.name = 'FastAPI', e.type = 'Technology', e.normalized_name = 'fastapi', e.aliases = [], e.aliases_text = '', e.document_ids = ['seed'];
MERGE (e:Entity:Technology {id: 'seed_' + $tenant_id + '_django'}) SET e.tenant_id = $tenant_id, e.name = 'Django', e.type = 'Technology', e.normalized_name = 'django', e.aliases = [], e.aliases_text = '', e.document_ids = ['seed'];
MERGE (e:Entity:Technology {id: 'seed_' + $tenant_id + '_neo4j'}) SET e.tenant_id = $tenant_id, e.name = 'Neo4j', e.type = 'Technology', e.normalized_name = 'neo4j', e.aliases = [], e.aliases_text = '', e.document_ids = ['seed'];
MERGE (e:Entity:Company {id: 'seed_' + $tenant_id + '_techcorp'}) SET e.tenant_id = $tenant_id, e.name = 'TechCorp', e.type = 'Company', e.normalized_name = 'techcorp', e.aliases = [], e.aliases_text = '', e.document_ids = ['seed'];
MERGE (e:Entity:Department {id: 'seed_' + $tenant_id + '_engineering_department'}) SET e.tenant_id = $tenant_id, e.name = 'Engineering Department', e.type = 'Department', e.normalized_name = 'engineering department', e.aliases = [], e.aliases_text = '', e.document_ids = ['seed'];
MERGE (e:Entity:Location {id: 'seed_' + $tenant_id + '_bangalore'}) SET e.tenant_id = $tenant_id, e.name = 'Bangalore', e.type = 'Location', e.normalized_name = 'bangalore', e.aliases = [], e.aliases_text = '', e.document_ids = ['seed'];

MATCH (s:Entity {id: 'seed_' + $tenant_id + '_rahul', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_project_alpha', tenant_id: $tenant_id}) MERGE (s)-[r:MANAGES]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Rahul manages Project Alpha';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_rahul', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_project_beta', tenant_id: $tenant_id}) MERGE (s)-[r:MANAGES]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Rahul manages Project Beta';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_priya', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_project_gamma', tenant_id: $tenant_id}) MERGE (s)-[r:MANAGES]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Priya manages Project Gamma';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_amit', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_project_alpha', tenant_id: $tenant_id}) MERGE (s)-[r:WORKS_ON]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Amit works on Project Alpha';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_neha', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_project_alpha', tenant_id: $tenant_id}) MERGE (s)-[r:WORKS_ON]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Neha works on Project Alpha';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_neha', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_project_gamma', tenant_id: $tenant_id}) MERGE (s)-[r:WORKS_ON]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Neha works on Project Gamma';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_priya', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_project_beta', tenant_id: $tenant_id}) MERGE (s)-[r:WORKS_ON]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Priya works on Project Beta';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_project_alpha', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_kafka', tenant_id: $tenant_id}) MERGE (s)-[r:USES]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Project Alpha uses Kafka';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_project_alpha', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_redis', tenant_id: $tenant_id}) MERGE (s)-[r:USES]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Project Alpha uses Redis';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_project_alpha', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_postgresql', tenant_id: $tenant_id}) MERGE (s)-[r:USES]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Project Alpha uses PostgreSQL';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_project_alpha', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_fastapi', tenant_id: $tenant_id}) MERGE (s)-[r:USES]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Project Alpha uses FastAPI';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_project_beta', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_django', tenant_id: $tenant_id}) MERGE (s)-[r:USES]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Project Beta uses Django';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_project_beta', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_postgresql', tenant_id: $tenant_id}) MERGE (s)-[r:USES]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Project Beta uses PostgreSQL';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_project_beta', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_redis', tenant_id: $tenant_id}) MERGE (s)-[r:USES]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Project Beta uses Redis';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_project_gamma', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_kafka', tenant_id: $tenant_id}) MERGE (s)-[r:USES]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Project Gamma uses Kafka';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_project_gamma', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_neo4j', tenant_id: $tenant_id}) MERGE (s)-[r:USES]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Project Gamma uses Neo4j';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_project_gamma', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_fastapi', tenant_id: $tenant_id}) MERGE (s)-[r:USES]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Project Gamma uses FastAPI';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_project_gamma', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_project_alpha', tenant_id: $tenant_id}) MERGE (s)-[r:DEPENDS_ON]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Project Gamma depends on Project Alpha';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_amit', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_kafka', tenant_id: $tenant_id}) MERGE (s)-[r:USES]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Amit uses Kafka';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_amit', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_redis', tenant_id: $tenant_id}) MERGE (s)-[r:USES]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Amit uses Redis';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_neha', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_fastapi', tenant_id: $tenant_id}) MERGE (s)-[r:USES]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Neha uses FastAPI';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_neha', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_kafka', tenant_id: $tenant_id}) MERGE (s)-[r:USES]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Neha uses Kafka';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_priya', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_neo4j', tenant_id: $tenant_id}) MERGE (s)-[r:USES]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Priya uses Neo4j';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_priya', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_django', tenant_id: $tenant_id}) MERGE (s)-[r:USES]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Priya uses Django';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_amit', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_rahul', tenant_id: $tenant_id}) MERGE (s)-[r:REPORTS_TO]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Amit reports to Rahul';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_neha', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_rahul', tenant_id: $tenant_id}) MERGE (s)-[r:REPORTS_TO]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Neha reports to Rahul';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_priya', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_rahul', tenant_id: $tenant_id}) MERGE (s)-[r:REPORTS_TO]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Priya reports to Rahul';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_rahul', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_techcorp', tenant_id: $tenant_id}) MERGE (s)-[r:WORKS_FOR]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Rahul works for TechCorp';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_amit', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_techcorp', tenant_id: $tenant_id}) MERGE (s)-[r:WORKS_FOR]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Amit works for TechCorp';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_priya', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_techcorp', tenant_id: $tenant_id}) MERGE (s)-[r:WORKS_FOR]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Priya works for TechCorp';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_neha', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_techcorp', tenant_id: $tenant_id}) MERGE (s)-[r:WORKS_FOR]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Neha works for TechCorp';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_rahul', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_engineering_department', tenant_id: $tenant_id}) MERGE (s)-[r:MANAGES]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Rahul manages Engineering Department';
MATCH (s:Entity {id: 'seed_' + $tenant_id + '_engineering_department', tenant_id: $tenant_id}), (t:Entity {id: 'seed_' + $tenant_id + '_bangalore', tenant_id: $tenant_id}) MERGE (s)-[r:BELONGS_TO]->(t) SET r.tenant_id = $tenant_id, r.document_ids = ['seed'], r.chunk_ids = [], r.evidence = 'Engineering Department belongs to Bangalore';
